name: Sync README to GitBook

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync README.md to GitBook
        env:
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITBOOK_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "files": [
                {
                  "path": "README.md",
                  "title": "Introduction"
                }
              ]
            }' \
            https://api.gitbook.com/v1/spaces/vcFb2GNNnzumOe4PqsTj/content
